---
title: "ExamFin_INF104"
author: "Peter  Frantzley CHARLES,Fabrice Salomon CHARLES,Sri Darwin BOIREAU,Bendy Widelph Adony LILITE"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(wbstats)
library(ggplot2)
library(dplyr)
library(formattable)
```


```{r main, include=FALSE}
# Importations de données 

taux_change <- wb_data(indicator = "PA.NUS.FCRF", country = "HTI",
                    start_date = 1988, end_date = 2021)

exportations<- wb_data(indicator= "NE.EXP.GNFS.ZS" , country = "HTI" ,
                    start_date = 1988, end_date = 2021)
importations<- wb_data(indicator = "NE.IMP.GNFS.CD", country = "HTI", 
                       start_date = 1988, end_date = 2021)
IDE<- wb_data(indicator="BX.KLT.DINV.WD.GD.ZS", country = "HTI",
                        start_date= 1988, end_date = 2021)

# Nettoyage des tableaux
taux_change<- taux_change[, c(3, 4, 5)]
exportations<- exportations[, c(5)]
importations<- importations[, c(5)]
IDE<- IDE[, c(5)]

# Tableaux combinés
tableau_combine<- cbind(taux_change, exportations,importations,IDE)

# Renommons les variables
colnames(tableau_combine)<- c("Pays", "Date", "Tauxdechange", "Exportations", "Importations", "IDE")

# Régression linéaire 

reg_lin<-summary(lm(Tauxdechange~Exportations+Importations+IDE,tableau_combine))


```

Introduction
===============================================================================

```{r echo=FALSE}
print("Nous avons choisi les variables de taux de change, d'exportations, d'importations et d'IDE (investissements directs étrangers) pour analyser la performance économique d'Haïti sur une période de 33 ans, de 1988 à 2021. Le taux de change est un indicateur important pour mesurer la compétitivité de la monnaie nationale sur les marchés internationaux. Avec les importations, le signe attendu est négatif(-) car toute augmentation du taux de change décourage les importations. Les exportations, elles, impactent le taux de change positivement car toute augmentation de celui-ci(dévaluation de la monnaie locale) engendre une augmentation des exportations. Enfin, les IDE sont un indicateur clé des flux de capitaux étrangers entrants mais sachant qu'ils dépendent de la stabilité politique et des règlementations économiques, le signe attendu du taux de change ne sera pas vraiment clair.")

```
Tableaux des variables
===============================================================================

### Tableau 1

```{r echo=FALSE}
print(tableau_combine)

```

Nuage de points
===============================================================================

### Graph A : Taux_de_change~Exportations

```{r echo=FALSE}
ggplot(data=tableau_combine, mapping=aes(x=Exportations,y=Tauxdechange)) + geom_point()+
labs(title = "Nuage de points|Exportaions ")+geom_smooth(method = "lm")

```
### Graph B : Taux_de_change~Importations

```{r echo=FALSE}
ggplot(data=tableau_combine, mapping=aes(x=Importations,y=Tauxdechange)) + geom_point()+
  labs(title = "Nuage de points|Importations ")+geom_smooth(method = "lm")

```

### Graph C : Taux_de_change~IDE

```{r echo=FALSE}
ggplot(data=tableau_combine, mapping=aes(x=IDE,y=Tauxdechange)) + geom_point()+
  labs(title = "Nuage de points|IDE")+geom_smooth(method = "lm")
```

Régression 
=========================================================================== 
### Tableau de regression 

```{r echo=FALSE}
print(reg_lin)

```


### Nuage de points valeurs résiduelles vs valleurs estimées 


```{r echo=FALSE}

plot(lm(Tauxdechange~Exportations+Importations+IDE,tableau_combine),
     main = "V.résiduelles vs V.estimées", which = 1) 

```

### Commentaires

```{r echo=FALSE}

print("Idéalement, on s'attendrait à ce que les points soient répartis de manière homogène aléatoire autour de l'axe y = 0, ce qui indiquerait que le modèle linéaire est approprié pour expliquer la variation de la variable dépendante.Cependant, il y a une légère tendance à l'hétéroscédasticité, ce qui pourrait être dû à la présence d'observations atypiques dont il faudrait vérifier la source.")

```
